BRICK = 0
BACKGROUND = 1
SHOOT = 2
ITEM = 3
SCROLL = 4
KEY = 5
MONSTER_1 = 6
DOOR = 7
STAIRS = 8
MONSTER_2 = 9
METAL = 10
REPAIR = 11
PLAYER = 100

ENTITY_TYPE_WALL = 0
ENTITY_TYPE_SPRITE = 1
ENTITY_TYPE_DIRECTIONAL_SPRITE = 2

ENTITY_TYPE_MAPPING = {
    BRICK: ENTITY_TYPE_WALL,
    BACKGROUND: ENTITY_TYPE_SPRITE,
    SHOOT: ENTITY_TYPE_SPRITE,
    ITEM: ENTITY_TYPE_SPRITE,
    SCROLL: ENTITY_TYPE_SPRITE,
    KEY: ENTITY_TYPE_SPRITE,
    MONSTER_1: ENTITY_TYPE_DIRECTIONAL_SPRITE,
    DOOR: ENTITY_TYPE_SPRITE,
    STAIRS: ENTITY_TYPE_SPRITE,
    MONSTER_2: ENTITY_TYPE_SPRITE,
    METAL: ENTITY_TYPE_SPRITE,
    REPAIR: ENTITY_TYPE_SPRITE,
}

ENTITY_TEXTURES = {
    BRICK: 'data/brick.png',
    BACKGROUND: 'data/background.png',
    SHOOT: 'data/shoot.png',
    ITEM: 'data/item.png',
    SCROLL: 'data/scroll.png',
    KEY: 'data/key.png',
    MONSTER_1: 'data/monster1',
    DOOR: 'data/door.png',
    STAIRS: 'data/stairs.png',
    MONSTER_2: 'data/monster2.png',
    METAL: 'data/metal.png',
    REPAIR: 'data/repair.png'
}
